import "./globals.css";
import type { Metadata } from "next";
import { Poppins } from "next/font/google";
import Sidebar from "./component/sidebar";
import Header from "./component/header";
import Providers from "./redux/providers";

const poppins = Poppins({
  subsets: ["latin"],
  display: "swap",
  variable: "--font-poppins",
  weight: ["300", "400", "500", "600", "700"],
});

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: {
  children: React.ReactNode;
}) {
  return (
    <Providers>
      <html lang="en">
        <body className={`flex h-[1400px] bg-gray-50/70 ${poppins.className}`}>
          <Sidebar />
          <div className="flex-1">
            <Header />
            <section className="flex w-full justify-center">{children}</section>
          </div>
        </body>
      </html>
    </Providers>
  );
}
